# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_EXYNOS5422_DMC)	+= exynos5422-dmc.o
exynos8890-dmc-driver-y		:= exynos8890-dmc.o exynos8890-dmc-timing.o
obj-$(CONFIG_EXYNOS8890_DMC)	+= exynos8890-dmc-driver.o
obj-$(CONFIG_EXYNOS_SROM)	+= exynos-srom.o
