# SPDX-License-Identifier: GPL-2.0
#
# herolte panel config only: S6E3HA3 dynamic-backlight WQHD panel.

obj-$(CONFIG_EXYNOS8890_DECON) += dsim_panel.o mdnie_lite.o lcd_sysfs.o \
	s6e3ha3_s6e3ha2_wqhd_lcd_ctrl.o dimming_core.o dsim_backlight_dynamic.o
obj-$(CONFIG_DISPLAY_USE_INFO) += dpui.o
