/* SPDX-License-Identifier: GPL-2.0-only OR BSD-2-Clause */
#ifndef _DT_BINDINGS_CLOCK_SAMSUNG_EXYNOS8890_CPU_H
#define _DT_BINDINGS_CLOCK_SAMSUNG_EXYNOS8890_CPU_H

#define EXYNOS8890_CPUCLK_APOLLO		0
#define EXYNOS8890_CPUCLK_MONGOOSE	1

#endif /* _DT_BINDINGS_CLOCK_SAMSUNG_EXYNOS8890_CPU_H */
